import { Product, Review, FAQItem, GalleryItem } from './types';

export const products: Product[] = [
  {
    id: 'baklava-royal',
    nameAr: 'بقلاوة ملكية بالفستق الحلبي',
    nameEn: 'Royal Pistachio Baklava',
    descriptionAr: 'رقائق عجين ذهبية هشة محشوة بأجود أنواع الفستق الحلبي الفاخر ومسقية بقطر ماء الورد الطبيعي والسمن البلدي.',
    descriptionEn: 'Crispy layers of golden phyllo dough, generously stuffed with premium pistachios, infused with pure orange blossom syrup and authentic ghee.',
    price: 120,
    image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=600&q=80',
    category: 'traditional',
    rating: 4.9,
    isPopular: true,
  },
  {
    id: 'kunafa-nabulsia',
    nameAr: 'كنافة نابلسية بالجبن',
    nameEn: 'Nabulsi Cheese Kunafa',
    descriptionAr: 'كنافة نابلسية تقليدية بخيوط العجين المقرمشة وجبنة عكاوي غنية تذوب مع كل قضم، مزينة بالفستق والقطر الساخن.',
    descriptionEn: 'Traditional Nabulsi Kunafa with crispy golden shredded pastry, rich melting Akkawi cheese, garnished with pistachios and hot syrup.',
    price: 85,
    image: 'https://images.unsplash.com/photo-1627308595229-7830a5c91f9f?auto=format&fit=crop&w=600&q=80',
    category: 'traditional',
    rating: 5.0,
    isPopular: true,
  },
  {
    id: 'maamoul-pistachio',
    nameAr: 'معمول فستق ملكي فاخر',
    nameEn: 'Royal Pistachio Maamoul',
    descriptionAr: 'بسكويت سميد تقليدي يذوب في الفم محشو بالفستق الحلبي الفاخر وماء الزهر، مرشوش بالسكر الناعم لتقديم أنيق.',
    descriptionEn: 'Mouth-watering melt-in-the-mouth semolina cookies packed with premium pistachios and orange blossom water, lightly dusted with powdered sugar.',
    price: 95,
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80',
    category: 'traditional',
    rating: 4.8,
  },
  {
    id: 'basbousa-almond',
    nameAr: 'بسبوسة باللوز والقشطة',
    nameEn: 'Almond & Cream Basbousa',
    descriptionAr: 'كعكة سميد طرية وغنية بجوز الهند والسمن البلدي، محشوة بالقشطة الطازجة ومزينة باللوز المحمص والقطر.',
    descriptionEn: 'Moist semolina cake with coconut, sweetened with honey syrup, layered with fresh traditional clotted cream and topped with roasted almonds.',
    price: 70,
    image: 'https://images.unsplash.com/photo-1600431521340-491eca880813?auto=format&fit=crop&w=600&q=80',
    category: 'traditional',
    rating: 4.7,
  },
  {
    id: 'halawet-jibn',
    nameAr: 'حلاوة الجبن الطازجة',
    nameEn: 'Fresh Halawet El-Jibn',
    descriptionAr: 'لفائف الجبن السميد الحلوة الطرية المحشوة بالقشطة البلدية الفاخرة، مزينة بزهر الليمون المربى ورشة فستق.',
    descriptionEn: 'Soft and delicate sweet cheese rolls stuffed with fresh authentic cream, drizzled with syrup and garnished with candied orange blossoms.',
    price: 80,
    image: 'https://images.unsplash.com/photo-1519676867240-f03562e64548?auto=format&fit=crop&w=600&q=80',
    category: 'traditional',
    rating: 4.9,
    isPopular: true,
  },
  {
    id: 'chocolate-luxury-box',
    nameAr: 'علبة شوكولاتة المغرف الفاخرة',
    nameEn: 'Al-Magharif Luxury Chocolate Box',
    descriptionAr: 'تشكيلة مختارة من الشوكولاتة المصنوعة يدوياً بنكهات مميزة تشمل الهيل، الزعفران، الفستق، والكراميل المملح.',
    descriptionEn: 'An exquisite selection of handcrafted chocolate truffles with unique Middle Eastern infusions including cardamom, saffron, pistachio, and salted caramel.',
    price: 180,
    image: 'https://images.unsplash.com/photo-1548907040-4d42b521251c?auto=format&fit=crop&w=600&q=80',
    category: 'chocolates',
    rating: 4.9,
    isPopular: true,
  },
  {
    id: 'croissant-almond',
    nameAr: 'كرواسون اللوز الباريسي',
    nameEn: 'Parisian Almond Croissant',
    descriptionAr: 'كرواسون زبدة فرنسي هش مخبوز طازجاً، محشو بكريمة اللوز الغنية ومغطى بشرائح اللوز المقرمشة وسكر البودرة.',
    descriptionEn: 'Flaky and buttery French croissant freshly baked, filled with rich almond frangipane, topped with sliced almonds and powdered sugar.',
    price: 18,
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=600&q=80',
    category: 'bakery',
    rating: 4.8,
  },
  {
    id: 'celebration-cake-pistachio',
    nameAr: 'كيكة الفستق والورد للمناسبات',
    nameEn: 'Celebration Pistachio & Rose Cake',
    descriptionAr: 'طبقات من كعكة الفستق الاسفنجية الرطبة المشربة بماء الورد، تفصلها كريمة الماسكاربوني المخفوقة وبتلات الورد الصالحة للأكل.',
    descriptionEn: 'Layers of moist pistachio sponge cake infused with organic rose water, separated by whipped mascarpone cheese and garnished with edible rose petals.',
    price: 250,
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=600&q=80',
    category: 'bakery',
    rating: 5.0,
    isPopular: true,
  },
  {
    id: 'salted-caramel-cupcakes',
    nameAr: 'كب كيك الكراميل المملح والذهب',
    nameEn: 'Salted Caramel & Gold Cupcakes',
    descriptionAr: 'ستة قطع كب كيك فانيليا غنية بقلب كراميل سائل، مغطاة بكريمة كراميل غنية وورق ذهب عيار 24 الصالح للأكل.',
    descriptionEn: 'Six delicate vanilla cupcakes with a molten salted caramel core, topped with whipped caramel buttercream and edible 24k gold flakes.',
    price: 65,
    image: 'https://images.unsplash.com/photo-1535141192574-5d4897c13636?auto=format&fit=crop&w=600&q=80',
    category: 'bakery',
    rating: 4.6,
  },
  {
    id: 'royal-gift-box',
    nameAr: 'صندوق الهدايا الملكي المخملي',
    nameEn: 'Royal Velvet VIP Gift Box',
    descriptionAr: 'صندوق مخملي فاخر باللون الأخضر الداكن والذهبي يحتوي على تشكيلة فاخرة من البقلاوة، المعمول، الملبس والشوكولاتة.',
    descriptionEn: 'A luxury deep emerald velvet box featuring hand-embossed gold details, filled with our premium baklava, maamoul, chocolate truffles, and almond dragées.',
    price: 320,
    image: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=600&q=80',
    category: 'gifts',
    rating: 5.0,
    isPopular: true,
  },
  {
    id: 'double-chocolate-cookies',
    nameAr: 'كوكيز الشوكولاتة المزدوجة البلجيكية',
    nameEn: 'Belgian Double Chocolate Cookies',
    descriptionAr: 'كوكيز طرية وداكنة محشوة بقطع شوكولاتة بلجيكية فاخرة ودافئة تذوب في الفم، مخبوزة يومياً.',
    descriptionEn: 'Rich, soft, and chewy cookies loaded with melting chunks of premium dark and milk Belgian chocolates, baked fresh daily.',
    price: 45,
    image: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?auto=format&fit=crop&w=600&q=80',
    category: 'chocolates',
    rating: 4.7,
  },
  {
    id: 'fudge-brownies-box',
    nameAr: 'علبة براونيز الفدج الفاخرة',
    nameEn: 'Gourmet Fudge Brownies Box',
    descriptionAr: 'ستة قطع من براونيز الكاكاو الغنية والطرية مع قشرة لامعة مقرمشة، مزينة بقطع شوكولاتة الجوز ورشة ملح بحري.',
    descriptionEn: 'Six pieces of ultra-fudgy chocolate brownies with a crackly top, loaded with toasted walnuts and sprinkled with flaky sea salt.',
    price: 55,
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=600&q=80',
    category: 'chocolates',
    rating: 4.8,
  }
];

export const reviews: Review[] = [
  {
    id: 'review-1',
    nameAr: 'فهد العتيبي',
    nameEn: 'Fahad Al-Otaibi',
    rating: 5,
    textAr: 'البقلاوة الملكية من حلويات المغرف هي الأفضل بلا منازع! الحشوة سخية جداً بالفستق والسمن البلدي طعمه واضح وممتاز. التغليف يبيض الوجه ومناسب جداً للهدايا.',
    textEn: 'The Royal Baklava from Al-Magharif is hands down the absolute best! Exquisitely packed with pistachios, and the high-quality ghee taste is pristine. Packaging is very premium and perfect for formal gifting.',
    dateAr: 'منذ يومين',
    dateEn: '2 days ago',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80'
  },
  {
    id: 'review-2',
    nameAr: 'ليلى الهاشمي',
    nameEn: 'Layla Al-Hashimi',
    rating: 5,
    textAr: 'طلبت كيكة الفستق والورد لعيد ميلاد زوجي وكانت تحفة فنية! طرية جداً ونكهة ماء الورد متوازنة تماماً وليست طاغية. كل الضيوف سألوني عن المحل.',
    textEn: 'I ordered the Pistachio & Rose cake for my husband\'s birthday, and it was a masterpiece! Incredibly moist and the rosewater flavor was perfectly balanced. All our guests loved it!',
    dateAr: 'منذ أسبوع',
    dateEn: '1 week ago',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80'
  },
  {
    id: 'review-3',
    nameAr: 'طارق منصور',
    nameEn: 'Tariq Mansoor',
    rating: 5,
    textAr: 'الكنافة النابلسية تصل دافئة والجبنة تمط بشكل رائع! القطر خفيف والحلويات كلها طازجة. تعامل راقي وتوصيل سريع جداً عبر الواتساب.',
    textEn: 'The Nabulsi Kunafa arrived warm, and the cheese pull was phenomenal! The syrup was light and everything felt fresh. High professionalism and exceptionally fast service via WhatsApp ordering.',
    dateAr: 'منذ أسبوعين',
    dateEn: '2 weeks ago',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80'
  }
];

export const faqs: FAQItem[] = [
  {
    id: 'faq-1',
    questionAr: 'هل يمكنني حجز كيكة خاصة ومخصصة للمناسبات؟',
    questionEn: 'Can I order a custom-designed celebration cake?',
    answerAr: 'نعم بكل سرور! نصنع كيكات مخصصة بامتياز لحفلات الزفاف، التخرج، وأعياد الميلاد. يرجى التواصل معنا عبر الواتساب قبل 48 ساعة على الأقل لتنسيق الحشوات والتصميم والتفاصيل الخاصة بك.',
    answerEn: 'Yes, absolutely! We craft bespoke custom cakes for weddings, graduations, and private events. Please connect with us on WhatsApp at least 48 hours in advance to finalize flavor layers, customized toppings, and delivery scheduling.'
  },
  {
    id: 'faq-2',
    questionAr: 'هل تقدمون خدمة تخصيص وتنسيق صناديق الهدايا؟',
    questionEn: 'Do you offer customized gift boxes for corporate or private events?',
    answerAr: 'نعم، نوفر خدمة تخصيص علب الهدايا للمؤسسات والمناسبات العائلية الكبرى، مع إمكانية إضافة شعار شركتكم أو بطاقات ترحيبية خاصة، وتعبئتها بالتشكيلة التي تختارونها من حلوياتنا الفاخرة.',
    answerEn: 'Yes! We customize corporate and luxury event gift boxes. We can incorporate your company logo, customized branding ribbon, or bespoke greeting cards, and pack them with your custom selection of premium Arabic sweets and chocolates.'
  },
  {
    id: 'faq-3',
    questionAr: 'ما هي مواعيد وطرق التوصيل المتاحة لديكم؟',
    questionEn: 'What are your delivery hours and service coverage?',
    answerAr: 'نقدم خدمة التوصيل السريع يومياً من الساعة 10:00 صباحاً وحتى الساعة 11:00 مساءً. جميع طلبيات الكنافة والحلويات الساخنة يتم نقلها في صناديق حرارية لضمان وصولها طازجة وساخنة.',
    answerEn: 'We provide express delivery daily from 10:00 AM to 11:00 PM. All hot kunafa and fresh warm items are transported in dedicated thermal boxes to ensure they arrive fresh, aromatic, and steaming hot.'
  },
  {
    id: 'faq-4',
    questionAr: 'كيف تضمنون جودة ونضارة الحلويات يومياً؟',
    questionEn: 'How do you guarantee the freshness of your bakery items?',
    answerAr: 'جميع منتجاتنا تُخبز طازجة يومياً في الصباح الباكر بمطبخنا المركزي، باستخدام مكونات طبيعية 100٪ بدون أي مواد حافظة، ونلتزم بأعلى معايير سلامة الأغذية والذوق الرفيع.',
    answerEn: 'All of our sweets and pastries are baked fresh every single morning in our central artisanal bakery using 100% natural, premium ingredients and zero preservatives, ensuring unmatched taste and absolute food safety.'
  },
  {
    id: 'faq-5',
    questionAr: 'ما هي طرق الدفع التي تقبلونها؟',
    questionEn: 'What payment methods do you accept?',
    answerAr: 'نقبل الدفع نقداً عند الاستلام، الدفع بالبطاقات الائتمانية (مدى، فيزا، ماستركارد)، التحويل البنكي المباشر، والدفع السريع عبر آبل باي لتسهيل وتسريع عملية الشراء.',
    answerEn: 'We accept Cash on Delivery, credit/debit cards (Mada, Visa, Mastercard), direct bank transfers, and seamless contactless mobile payments including Apple Pay for a completely secure experience.'
  }
];

export const galleryItems: GalleryItem[] = [
  {
    id: 'g-1',
    image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=800&q=80',
    titleAr: 'صينية البقلاوة الملكية الساخنة',
    titleEn: 'Fresh Golden Royal Baklava Tray',
    category: 'sweets'
  },
  {
    id: 'g-2',
    image: 'https://images.unsplash.com/photo-1627308595229-7830a5c91f9f?auto=format&fit=crop&w=800&q=80',
    titleAr: 'الكنافة النابلسية الشهية بالجبن الفاخر',
    titleEn: 'Signature Cheesy Nabulsi Kunafa',
    category: 'sweets'
  },
  {
    id: 'g-3',
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80',
    titleAr: 'كعكات المناسبات وأعياد الميلاد المصنوعة يدوياً',
    titleEn: 'Artisanal Custom Celebration Cakes',
    category: 'cakes'
  },
  {
    id: 'g-4',
    image: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=800&q=80',
    titleAr: 'صناديق الهدايا والمناسبات الفخمة',
    titleEn: 'Royal Emerald Gold Gift Packing',
    category: 'gifts'
  },
  {
    id: 'g-5',
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=800&q=80',
    titleAr: 'المعجنات والكرواسون الساخن المخبوز يومياً',
    titleEn: 'Buttery French Croissants Baked Daily',
    category: 'bakery'
  },
  {
    id: 'g-6',
    image: 'https://images.unsplash.com/photo-1548907040-4d42b521251c?auto=format&fit=crop&w=800&q=80',
    titleAr: 'علب الشوكولاتة البلجيكية المحشوة يدوياً',
    titleEn: 'Handmade Belgian Chocolates Truffles',
    category: 'gifts'
  }
];

export const translations = {
  ar: {
    brandName: 'حلويات المغرف',
    brandSub: 'أصالة المذاق وفخامة الضيافة',
    navHome: 'الرئيسية',
    navAbout: 'قصتنا',
    navMenu: 'قائمة الحلويات',
    navWhyUs: 'مميزاتنا',
    navGallery: 'المعرض',
    navReviews: 'آراء عملائنا',
    navFaq: 'الأسئلة الشائعة',
    navContact: 'تواصل معنا',
    orderNow: 'اطلب الآن',
    viewMenu: 'تصفح القائمة',
    heroTitle: 'حلويات عربية أصيلة تُصنع بحب',
    heroSub: 'اكتشف روعة المذاق مع تشكيلتنا الفاخرة من الحلويات العربية التقليدية، الكنافة النابلسية الساخنة، الكيكات الفاخرة، المخبوزات الطازجة، والشوكولاتة المصنوعة بأيدي أمهر الخبراء وأجود المكونات الطبيعية.',
    aboutTitle: 'حكاية الشغف والأصالة',
    aboutSub: 'كيف بدأت رحلتنا في حلويات المغرف؟',
    aboutText1: 'في "حلويات المغرف"، نؤمن بأن صنع الحلويات ليس مجرد مهنة، بل هو فن عريق ينتقل عبر الأجيال. تأسس متجرنا على رغبة راسخة في إحياء وحفظ التراث الغني للحلويات العربية التقليدية، مع إضافة لمسة عصرية من الفخامة والابتكار تليق بمناسباتكم السعيدة.',
    aboutText2: 'نحن ننتقي مكوناتنا بمنتهى العناية؛ من الفستق الحلبي الطازج والسمن البلدي النقي، إلى الشوكولاتة البلجيكية الفاخرة وأوراق الذهب القابلة للأكل. كل قطعة تخرج من مخابزنا هي ثمرة ساعات من الحب والدقة، لتقديم طعم يأخذكم في رحلة من الذكريات الجميلة واللحظات التي لا تُنسى.',
    aboutBadge: 'شغف، إتقان، وذوق رفيع',
    whyTitle: 'لماذا يختارنا عشاق الحلويات؟',
    whySub: 'سر تميزنا وفلسفة جودتنا اليومية',
    why1Title: 'وصفات عربية أصيلة',
    why1Desc: 'نلتزم بالوصفات التقليدية المتوارثة لنحافظ على النكهة الحقيقية والأصلية للحلويات التراثية.',
    why2Title: 'طازج يومياً',
    why2Desc: 'تُخبز جميع منتجاتنا طازجة يومياً في الصباح الباكر لتصلكم بأعلى مستويات الجودة والنضارة.',
    why3Title: 'مكونات فائقة الفخامة',
    why3Desc: 'نستخدم أفضل المكونات الطبيعية 100% كالسمن البلدي النقي، الفستق الطازج والزعفران الحر.',
    why4Title: 'علب هدايا فاخرة',
    why4Desc: 'تغليف ملكي أنيق ومصمم بعناية ليجعل من هداياكم تحفة فنية تليق بمن تحبون في كل مناسبة.',
    why5Title: 'طلبات مخصصة بالكامل',
    why5Desc: 'نصمم وننفذ كيكات وصناديق مناسباتكم الكبرى بما يتناسب مع رغباتكم وتفاصيلكم الفريدة.',
    why6Title: 'خدمة عملاء ممتازة',
    why6Desc: 'فريق شغوف ومستعد لمساعدتكم في كل خطوة، بدءاً من الطلب وحتى التوصيل السريع لباب منزلكم.',
    menuTitle: 'قائمة المذاق الفاخر',
    menuSub: 'اختر نكهتك المفضلة واطلبها فوراً عبر الواتساب',
    catAll: 'الكل',
    catTraditional: 'حلويات شرقية',
    catBakery: 'مخبوزات وكيك',
    catChocolates: 'شوكولاتة وبسكويت',
    catGifts: 'صناديق هدايا',
    searchPlaceholder: 'ابحث عن حلوياتك المفضلة...',
    popular: 'الأكثر طلباً',
    addToCart: 'إضافة للطلب',
    addedToCart: 'تمت الإضافة',
    cartTitle: 'تفاصيل طلبك الفاخر',
    cartEmpty: 'سلتك فارغة حالياً. تصفح قائمتنا واختر ما تشتهيه من حلويات!',
    cartTotal: 'المجموع الإجمالي:',
    cartGiftLabel: 'رسالة إهداء خاصة (اختياري):',
    cartGiftPlaceholder: 'اكتب إهداءً جميلاً هنا إذا كان هذا الطلب هدية لشخص عزيز...',
    cartSendBtn: 'إرسال الطلب عبر واتساب 💬',
    currency: 'ريال',
    galleryTitle: 'معرض الإبداع والجمال',
    gallerySub: 'لمحات بصرية من مطبخنا وصالة الضيافة لدينا',
    reviewTitle: 'شهادات نعتز بها',
    reviewSub: 'ماذا يقول عشاق حلويات المغرف عن تجربتهم؟',
    reviewSubmitBtn: 'شاركنا تقييمك الخاص',
    reviewFormTitle: 'أضف تقييمك وتجربتك',
    reviewFormName: 'الاسم الكريم',
    reviewFormRating: 'التقييم',
    reviewFormText: 'اكتب تجربتك هنا بكل أمانة ورأيك بالمنتجات والخدمة...',
    reviewFormSubmit: 'إرسال التقييم الآن',
    reviewSuccess: 'شكراً جزيلاً لتقييمك الرائع! تم نشر رأيك بنجاح وسيسعد فريقنا بقراءته.',
    faqTitle: 'الأسئلة الشائعة',
    faqSub: 'كل ما تود معرفته عن حلويات المغرف والطلبات',
    contactTitle: 'تواصل معنا ودعنا نسعدك',
    contactSub: 'نحن هنا للإجابة على جميع استفساراتكم واستقبال طلباتكم الكبرى',
    contactFormName: 'الاسم الكامل',
    contactFormEmail: 'البريد الإلكتروني',
    contactFormPhone: 'رقم الجوال',
    contactFormSubject: 'الموضوع',
    contactFormMsg: 'رسالتك الكريمة',
    contactFormSubmit: 'إرسال الرسالة الآن',
    contactFormSuccess: 'تم إرسال رسالتك بنجاح وسيقوم فريق خدمة العملاء بالتواصل معك في أقرب وقت ممكن!',
    contactInfoTitle: 'معلومات المتجر والضيافة',
    addressLabel: 'العنوان وموقع المحل:',
    addressValue: 'طريق الأمير محمد بن عبدالعزيز، السليمانية، الرياض، المملكة العربية السعودية',
    phoneLabel: 'رقم الهاتف المباشر:',
    emailLabel: 'البريد الإلكتروني الرسمي:',
    hoursLabel: 'ساعات العمل اليومية:',
    hoursValue: 'يومياً: 10:00 صباحاً - 11:30 مساءً',
    whatsappQuickBtn: 'محادثة سريعة عبر الواتساب',
    mapPlaceholder: 'موقعنا التفاعلي على الخريطة',
    footerAbout: 'تأسست حلويات المغرف لتقديم أفخر أنواع الحلويات الشرقية والمخبوزات العصرية والشوكولاتة الملكية في المملكة العربية السعودية، ملتزمين بالوصفات الأصيلة والمكونات الطبيعية الممتازة لضمان أقصى درجات الضيافة والبهجة في مناسباتكم السعيدة.',
    footerLegal: 'الحقوق والسياسات',
    footerPrivacy: 'سياسة الخصوصية والأمان',
    footerTerms: 'الشروط والأحكام والضيافة',
    footerRefund: 'سياسة الاستبدال والاسترجاع',
    footerRights: 'جميع الحقوق محفوظة لحلويات المغرف © 2026',
    close: 'إغلاق',
    qty: 'الكمية',
    customGiftMsg: 'رسالة إهداء: '
  },
  en: {
    brandName: 'Al-Magharif Sweets',
    brandSub: 'Authentic Taste & Royal Hospitality',
    navHome: 'Home',
    navAbout: 'Our Story',
    navMenu: 'Sweets Menu',
    navWhyUs: 'Why Choose Us',
    navGallery: 'Gallery',
    navReviews: 'Testimonials',
    navFaq: 'FAQ',
    navContact: 'Contact Us',
    orderNow: 'Order Now',
    viewMenu: 'Explore Menu',
    heroTitle: 'Authentic Arabic Sweets Crafted with Love',
    heroSub: 'Discover handcrafted premium Arabic sweets, piping hot Nabulsi cheese kunafa, exquisite celebration cakes, golden baked pastries, and luxury chocolates, made with the finest natural ingredients and traditional recipes.',
    aboutTitle: 'A Legacy of Passion & Quality',
    aboutSub: 'How the Al-Magharif Journey Began',
    aboutText1: 'At Al-Magharif Sweets, we believe that pastry making is not just a business, but a noble art passed down through generations. Our brand was born out of a profound passion to celebrate, preserve, and elevate the rich heritage of traditional Middle Eastern sweets, combined with a contemporary touch of luxury.',
    aboutText2: 'We select our ingredients with uncompromising precision: premium Turkish pistachios, authentic organic ghee, handpicked saffron, high-end Belgian chocolates, and delicate 24k edible gold leaf. Every product is a masterpiece created to evoke warm memories and deliver pure, luxurious joy.',
    aboutBadge: 'Passion, Perfection, and Elegance',
    whyTitle: 'Why Sweet Lovers Choose Us?',
    whySub: 'Our Uncompromising Philosophy of Daily Quality',
    why1Title: 'Authentic Arabic Recipes',
    why1Desc: 'We strictly adhere to centuries-old traditional recipes to guarantee the true, genuine taste of heritage sweets.',
    why2Title: 'Baked Fresh Daily',
    why2Desc: 'All our pastries and baklava are prepared and baked fresh every single morning to ensure perfect crispiness.',
    why3Title: 'Super-Premium Ingredients',
    why3Desc: 'We use premium natural ingredients: pure traditional ghee, fresh pistachios, and organic raw honey.',
    why4Title: 'Luxury Gift Packaging',
    why4Desc: 'Our signature royal boxes with gold-foil accents make our sweets the most elegant gift for those you cherish.',
    why5Title: 'Fully Bespoke Orders',
    why5Desc: 'We design and craft fully custom cakes and personalized sweets arrangements to match your major events.',
    why6Title: 'Excellent Service',
    why6Desc: 'A passionate team committed to ensuring an extraordinary experience, from custom ordering to swift door-step delivery.',
    menuTitle: 'Our Exquisite Menu',
    menuSub: 'Select your favorites and instantly place an order via WhatsApp',
    catAll: 'All Categories',
    catTraditional: 'Arabic Sweets',
    catBakery: 'Cakes & Bakery',
    catChocolates: 'Chocolates & Cookies',
    catGifts: 'Premium Gift Boxes',
    searchPlaceholder: 'Search for your favorite dessert...',
    popular: 'Best Seller',
    addToCart: 'Add to Order',
    addedToCart: 'Added to Cart',
    cartTitle: 'Your Exquisite Order Details',
    cartEmpty: 'Your cart is currently empty. Explore our luxurious menu and add your favorite treats!',
    cartTotal: 'Subtotal Amount:',
    cartGiftLabel: 'Bespoke Gift Message (Optional):',
    cartGiftPlaceholder: 'Write a beautiful greeting card message here if this order is a gift for someone special...',
    cartSendBtn: 'Place Order via WhatsApp 💬',
    currency: 'SAR',
    galleryTitle: 'Visual Symphony',
    gallerySub: 'A sneak peek inside our luxury kitchen and boutique storefront',
    reviewTitle: 'Cherished Words',
    reviewSub: 'What do dessert enthusiasts say about Al-Magharif Sweets?',
    reviewSubmitBtn: 'Write a Review',
    reviewFormTitle: 'Share Your Experience',
    reviewFormName: 'Your Full Name',
    reviewFormRating: 'Rating Stars',
    reviewFormText: 'Write your honest review and experience with our sweets, packaging, or service...',
    reviewFormSubmit: 'Submit Your Review',
    reviewSuccess: 'Thank you so much for your spectacular feedback! Your review has been added successfully.',
    faqTitle: 'Frequently Asked Questions',
    faqSub: 'Everything you need to know about Al-Magharif sweets & custom orders',
    contactTitle: 'Reach Out to Us',
    contactSub: 'We are delighted to assist you with daily cravings, customized setups, or large catering events',
    contactFormName: 'Full Name',
    contactFormEmail: 'Email Address',
    contactFormPhone: 'Phone Number',
    contactFormSubject: 'Subject',
    contactFormMsg: 'Your Message',
    contactFormSubmit: 'Send Message Now',
    contactFormSuccess: 'Your message has been successfully delivered! Our hospitality team will contact you shortly.',
    contactInfoTitle: 'Boutique Store & Hours',
    addressLabel: 'Boutique Location:',
    addressValue: 'Prince Muhammad bin Abdulaziz Road, As-Sulimaniyah, Riyadh, Saudi Arabia',
    phoneLabel: 'Direct Hotline:',
    emailLabel: 'Boutique Email:',
    hoursLabel: 'Boutique Opening Hours:',
    hoursValue: 'Daily: 10:00 AM - 11:30 PM',
    whatsappQuickBtn: 'Quick WhatsApp Live Chat',
    mapPlaceholder: 'Our Interactive Location Map',
    footerAbout: 'Al-Magharif Sweets was established to provide the finest Eastern sweets, contemporary cakes, and handcrafted chocolates in Saudi Arabia, using heritage recipes and top-tier organic ingredients to bring joy to all of your sweet celebrations.',
    footerLegal: 'Legal & Policies',
    footerPrivacy: 'Privacy & Security Policy',
    footerTerms: 'Terms of Service & Hospitality',
    footerRefund: 'Refund & Exchange Policies',
    footerRights: 'All rights reserved to Al-Magharif Sweets © 2026',
    close: 'Close',
    qty: 'Qty',
    customGiftMsg: 'Gift Message: '
  }
};
